#!/usr/bin/python3

import os
from datetime import datetime

# Domino design parameters. 
PIP_DEPTH = -2.0        # How deep to drill the pip from the surface of the domino
PIP_DIA = 4.0           # The diameter of the pip at the PIP_DEPTH - could be different if using v-bit vs drill.
PIP_MAX_SQUARE = 18.0   # The pip pattern will fill to the extents of this boundary.
L_ORIGIN_X = 12.7       # X-coord for the center of the left half of the domino.
L_ORIGIN_Y = -12.7      # Y-coord for the center of the left half of the domino.
R_ORIGIN_X = 38.1       # X-coord for the center of the right half of the domino.
R_ORIGIN_Y = -12.7      # Y-coord for the center of the right half of the domino.
BISECT_DEPTH = -1.0     # Depth to mill the domino bisect mark.
BISECT_WIDTH = 2.0      # Diameter formed on domino surface at BISECT_DEPTH for the tool making the bisect mark. 
BISECT_LENGTH = PIP_MAX_SQUARE - BISECT_WIDTH - PIP_DIA     # Length of the bisect mark.
DO_BISECT = True        # Do generate the bisect gcode if true, else do not.

# Machining parameters
R_PLANE = 0.7           # mm above part
Z_RETRACT = 2.5         # mm above part
DRILL_FEED = 100.0      # mm/min
SPINDLE_RPM = 2800.0    # Spindle speed in revolutions per miniute.

PART_CHANGE__X  = 5.0   # Location where we will change out to the next domino.
PART_CHANGE__Y  = 30.0

# File Names
FILENAME = os.path.basename(__file__)
DATETIME = datetime.now().strftime("%Y/%m/%d, %H:%M:%S")
file_created = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
OUTFILE = f"{file_created}-domino-set.ngc" # The filename of the output G-Code program.

# Returns the maximum orthogonal travel which keeps pips at the extremes of the pattern boundary square.
def max_pattern_ortho_dist(max_square, pip_dia_at_depth):
    return (max_square - pip_dia_at_depth)

# Go to part change location and pause. Swap part, then click resume in linuxcnc to go to next domino
def next_domino():
    ret_str = "\n(Put a new domino in the work holding.) ;\n"
    ret_str += "M05 (Stop spindle.) ;\n"
    ret_str += f"G00 X{PART_CHANGE__X} Y{PART_CHANGE__Y} (Rapid to part change location.) ;\n"
    ret_str += "M0 (Pause for part change.) ;\n"
    ret_str += f"S{SPINDLE_RPM} M03 (Start spindle.) ;\n"
    return ret_str

def bisect_domino(msg, bisect_len, bisect_depth):

    domino_center_x = ( R_ORIGIN_X - L_ORIGIN_X ) / 2 + L_ORIGIN_X
    bisect_start = L_ORIGIN_Y + ( bisect_len / 2.0 )
    bisect_end = bisect_start - bisect_len

    ret_str = f"({msg} of length {bisect_len} starting at X:{domino_center_x:.2f},Y:{bisect_start:.2f}) ;\n"
    ret_str += f"G00 X{domino_center_x:.2f} Y{bisect_start:.2f} (Rapid to bisect start location.) ;\n"
    ret_str += f"G01 F{DRILL_FEED} Z{bisect_depth} (Mill to bisect depth) ;\n"
    ret_str += f"G01 F{DRILL_FEED} Y{bisect_end} (Mill to bisect end position) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"
    
    if not DO_BISECT:
        ret_str = "(Do not make domino bisect mark.) ;\n"

    return ret_str

def gcode_header():

    ret_str = "%\n"
    ret_str += f"(Generated by {FILENAME} on {DATETIME}) ;\n"
    ret_str += "(G54 X0 Y0 is at the top-left of part) ;\n"
    ret_str += "(Z0 is on top of the part) ;\n"
    ret_str += f"(Tool produces a {PIP_DIA} diameter hole at domino top plane Z=0.0) ;\n"
    ret_str += f"(Machine spindle operates at {SPINDLE_RPM} RPM.) ;\n"
    ret_str += "(BEGIN PREPARATION BLOCKS) ;\n"
    ret_str += "T1 M06 (Select tool 1) ;\n"
    ret_str += "G00 G90 G40 G49 G54 (Safe startup) ;\n"
    ret_str += "G21 (Programming in mm) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"
    ret_str += f"S{SPINDLE_RPM} M03 (Start spindle.) ;\n"
    ret_str += f"M0 (Pause to set/verify spindle is at {SPINDLE_RPM} RPM.) ;\n"
    ret_str += "M05 (Stop spindle.) ;\n"
    return ret_str

def gcode_footer():
    ret_str = "\n"
    ret_str += "(BEGIN COMPLETION BLOCKS) ;\n"
    ret_str += "M05 (Stop spindle.) ;\n"
    ret_str += f"G00 X{PART_CHANGE__X} Y{PART_CHANGE__Y} (Rapid to part change location.) ;\n"
    ret_str += "M30 (End program) ;\n"
    ret_str += "%\n"
    return ret_str

def one_pip(msg, pattern_x,pattern_y, pip_depth):
    ret_str = f"({msg} at X:{pattern_x:.2f},Y:{pattern_y:.2f}) ;\n"

    ret_str += f"G00 X{pattern_x:.2f} Y{pattern_y:.2f} (Rapid to pattern center.) ;\n"

    ret_str += f"G81 Z{pip_depth} R{R_PLANE} F{DRILL_FEED} (Begin drill cycle.) ;\n"

    ret_str += "G80 (Cancel drill cycle.) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"

    return ret_str

def two_pips(msg, pattern_x,pattern_y, max_square, pip_depth, pip_dia_at_depth):
    ret_str = f"({msg} at X:{pattern_x:.2f},Y:{pattern_y:.2f}) ;\n"

    #ret_str += f"G00 X{pattern_x:.2f} Y{pattern_y:.2f} (Rapid to pattern center.) ;\n"
    
    max_travel = max_pattern_ortho_dist(max_square, pip_dia_at_depth)
    half_max_travel = max_travel/2.0

    hole_0 = (pattern_x-half_max_travel, pattern_y+half_max_travel)
    hole_1 = (pattern_x+half_max_travel, pattern_y-half_max_travel)
    
    ret_str += f"G00 X{hole_0[0]:.2f} Y{hole_0[1]:.2f} (Rapid to top-left pip.) ;\n"

    ret_str += f"G81 Z{pip_depth} R{R_PLANE} F{DRILL_FEED} (Begin drill cycle.) ;\n"
    ret_str += f"X{hole_1[0]:.2f} Y{hole_1[1]:.2f} (2nd hole) ;\n"

    ret_str += "G80 (Cancel drill cycle.) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"

    return ret_str

def four_pips(msg, pattern_x,pattern_y, max_square, pip_depth, pip_dia_at_depth):
    ret_str = f"({msg} at X:{pattern_x:.2f},Y:{pattern_y:.2f}) ;\n"

    #ret_str += f"G00 X{pattern_x:.2f} Y{pattern_y:.2f} (Rapid to pattern center.) ;\n"
    
    max_travel = max_pattern_ortho_dist(max_square, pip_dia_at_depth)
    half_max_travel = max_travel/2.0

    hole_0 = (pattern_x-half_max_travel, pattern_y+half_max_travel)
    hole_1 = (pattern_x+half_max_travel, pattern_y+half_max_travel)
    hole_2 = (pattern_x+half_max_travel, pattern_y-half_max_travel)
    hole_3 = (pattern_x-half_max_travel, pattern_y-half_max_travel)

    ret_str += f"G00 X{hole_0[0]:.2f} Y{hole_0[1]:.2f} (Rapid to top-left pip.) ;\n"

    ret_str += f"G81 Z{pip_depth} R{R_PLANE} F{DRILL_FEED} (Begin drill cycle.) ;\n"
    ret_str += f"X{hole_1[0]:.2f} Y{hole_1[1]:.2f} (2nd hole) ;\n"
    ret_str += f"X{hole_2[0]:.2f} Y{hole_2[1]:.2f} (3rd hole) ;\n"
    ret_str += f"X{hole_3[0]:.2f} Y{hole_3[1]:.2f} (4th hole) ;\n"

    ret_str += "G80 (Cancel drill cycle.) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"

    return ret_str

def six_pips(msg, pattern_x,pattern_y, max_square, pip_depth, pip_dia_at_depth):
    ret_str = f"({msg} at X:{pattern_x:.2f},Y:{pattern_y:.2f}) ;\n"

    #ret_str += f"G00 X{pattern_x:.2f} Y{pattern_y:.2f} (Rapid to pattern center.) ;\n"
    
    max_travel = max_pattern_ortho_dist(max_square, pip_dia_at_depth)
    half_max_travel = max_travel/2.0

    hole_0 = (pattern_x-half_max_travel, pattern_y+half_max_travel)
    hole_1 = (pattern_x, pattern_y+half_max_travel)
    hole_2 = (pattern_x+half_max_travel, pattern_y+half_max_travel)
    hole_3 = (pattern_x+half_max_travel, pattern_y-half_max_travel)
    hole_4 = (pattern_x, pattern_y-half_max_travel)
    hole_5 = (pattern_x-half_max_travel, pattern_y-half_max_travel)

    ret_str += f"G00 X{hole_0[0]:.2f} Y{hole_0[1]:.2f} (Rapid to top-left pip.) ;\n"
    ret_str += f"G81 Z{pip_depth} R{R_PLANE} F{DRILL_FEED} (Begin drill cycle.) ;\n"
    ret_str += f"X{hole_1[0]:.2f} Y{hole_1[1]:.2f} (2nd hole) ;\n"
    ret_str += f"X{hole_2[0]:.2f} Y{hole_2[1]:.2f} (3rd hole) ;\n"
    ret_str += f"X{hole_3[0]:.2f} Y{hole_3[1]:.2f} (4th hole) ;\n"
    ret_str += f"X{hole_4[0]:.2f} Y{hole_4[1]:.2f} (5th hole) ;\n"
    ret_str += f"X{hole_5[0]:.2f} Y{hole_5[1]:.2f} (6th hole) ;\n"

    ret_str += "G80 (Cancel drill cycle.) ;\n"
    ret_str += f"G00 G90 Z{Z_RETRACT} (Rapid retract) ;\n"

    return ret_str

def main():
    with open(OUTFILE,'w',encoding = "utf-8") as f:
        f.write(gcode_header())

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x0 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write("(~~~~~~~~~~ End 0x0 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x1 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write("(~~~~~~~~~~ End 0x1 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x2 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 0x2 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x3 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 0x3 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x4 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 0x4 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 0x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 0x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 0x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())
        
        f.write("\n(~~~~~~~~~~ Start 1x1 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write("(~~~~~~~~~~ End 1x1 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 1x2 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 1x2 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 1x3 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 1x3 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 1x4 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 1x4 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 1x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 1x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 1x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 1x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 2x2 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 2x2 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 2x3 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 2x3 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 2x4 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 2x4 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 2x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 2x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 2x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 2x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 3x3 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 3x3 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 3x4 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 3x4 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 3x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 3x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 3x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(two_pips("BEGIN 2-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 3x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 4x4 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 4x4 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 4x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 4x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 4x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 4x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 5x5 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(one_pip("BEGIN 1-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 5x5 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 5x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(one_pip("BEGIN 1-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_DEPTH))
        f.write(four_pips("BEGIN 4-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 5x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(next_domino())

        f.write("\n(~~~~~~~~~~ Start 6x6 Domino. ~~~~~~~~~~) ;\n")
        f.write(bisect_domino("BEGIN DOMINO BISECT MARK", BISECT_LENGTH, BISECT_DEPTH))
        f.write(six_pips("BEGIN 6-PIP PATTERN", L_ORIGIN_X, L_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("\n")
        f.write(six_pips("BEGIN 6-PIP PATTERN", R_ORIGIN_X, R_ORIGIN_Y, PIP_MAX_SQUARE, PIP_DEPTH,PIP_DIA))
        f.write("(~~~~~~~~~~ End 6x6 Domino. ~~~~~~~~~~) ;\n")

        f.write(gcode_footer())

if __name__ == "__main__":
    main()